"""add plan_days.theme

Revision ID: baf27cd8977f
Revises: 7f959c9c30b8
Create Date: 2026-09-23 14:49:13.233171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'baf27cd8977f'
down_revision: Union[str, Sequence[str], None] = '7f959c9c30b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plan_days', sa.Column('theme', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plan_days', 'theme')
    # ### end Alembic commands ###
